export const AllTypesProps: Record<string,any> = {
	Query:{
		search:{
			query:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		question:{
			_id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	UserMutation:{
		postQuestion:{
			createQuestion:{
				type:"CreateQuestion",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		postAnswer:{
			createAnswer:{
				type:"CreateAnswer",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		vote:{
			_id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	PublicMutation:{
		login:{
			login:{
				type:"Login",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		validateOtp:{
			validateOTP:{
				type:"ValidateOTP",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	Login:{
		username:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		phone:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	ValidateOTP:{
		phone:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		otp:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateQuestion:{
		content:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateAnswer:{
		content:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		to:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	Message:{
		"...on Question": "Question",
		"...on Answer": "Answer",
		content:"String",
		score:"Int"
	},
	StringId:{
		"...on Question": "Question",
		"...on Answer": "Answer",
		_id:"String"
	},
	Question:{
		content:"String",
		score:"Int",
		_id:"String",
		answers:"Answer",
		title:"String",
		createdAt:"String",
		updatedAt:"String",
		user:"User"
	},
	Answer:{
		content:"String",
		score:"Int",
		_id:"String",
		to:"ToAnswer",
		createdAt:"String",
		updatedAt:"String",
		user:"User",
		answers:"Answer"
	},
	Query:{
		search:"QuestionsResponse",
		question:"Question"
	},
	QuestionsResponse:{
		question:"Question",
		bestAnswer:"Answer"
	},
	Mutation:{
		user:"UserMutation",
		public:"PublicMutation"
	},
	UserMutation:{
		postQuestion:"String",
		postAnswer:"String",
		vote:"Int"
	},
	PublicMutation:{
		login:"String",
		validateOtp:"String"
	},
	ToAnswer:{
		"...on Question":"Question",
		"...on Answer":"Answer"
	},
	User:{
		username:"String"
	},
	Dated:{
		"...on Question": "Question",
		"...on Answer": "Answer",
		createdAt:"String",
		updatedAt:"String"
	},
	Owned:{
		"...on Question": "Question",
		"...on Answer": "Answer",
		user:"User"
	}
}